Update to 6.1.19

diff --git a/dist/s_sql_upgrade b/dist/s_sql_upgrade
--- a/dist/s_sql_upgrade
+++ b/dist/s_sql_upgrade
@@ -19,6 +19,29 @@ copy_if_changes()
 	rm -f $f2
 }
 
+# Check or recheck-and-apply each patch
+try_patches()
+{
+	doit=$1
+	for f in $sqldir/../adapter/sqlite-patches/[0-9][0-9]_*.patch ; do
+		msgs=$( patch -d $sqldir -p0 --dry-run --force < $f 2>&1 )
+		if test $? -ne 0 ;  then
+			echo "Patch $f would fail:"
+			echo "$msgs" | sed -e 's/^/	/'
+			echo "Exiting."
+			exit 1
+		else
+			if test $doit = 1 ; then
+				echo "Applying patch $f"
+				patch -d $sqldir -p0 --force --quiet < $f
+			fi
+		fi
+	done
+}
+
+# echo "Testing patch files for the sqlite source tree."
+# try_patches 0
+
 # Update the SQLite Makefile to refer to the replaced source files.
 MAKEFILE_NAME=$sqldir/Makefile.in
 for f in ../lang/sql/adapter/*.[ch]; do
@@ -36,15 +59,7 @@ sed -e 's/TOP = \.\.\/sqlite/TOP = \.\.\/\.\.\/sql\/sqlite/' $sqldir/Makefile.li
 copy_if_changes $sqldir/Makefile.linux-gcc $sqldir/Makefile.linux-gcc.tmp
 
 echo "Applying patch files to the sqlite source tree."
-for f in $sqldir/../adapter/sqlite-patches/[0-9][0-9]_*.patch ; do
-	if (cd $sqldir && patch -p0 --dry-run --force --quiet) < $f > /dev/null; then
-		echo "Applying patch $f"
-		(cd $sqldir && patch -p0 --force --quiet) < $f
-	else
-		echo "Patch $f would fail. Exiting."
-		exit 1
-	fi
-done
+try_patches 1
 
 # Remove files from the SQLite source tree that have been replaced by db.
 ( cd $sqldir/../adapter &&
